# Generated by Django 3.0.8 on 2022-05-20 07:06

import KyvorPipeline.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(max_length=120)),
                ('analysis_ref_id', models.CharField(max_length=20)),
                ('analysis_status', models.CharField(max_length=120)),
                ('analysis_description', models.TextField(blank=True, null=True)),
                ('analysis_timestamp', models.DateTimeField(auto_now_add=True)),
                ('bs_analysis_id', models.CharField(blank=True, max_length=120, null=True)),
                ('bs_analysis_status', models.CharField(blank=True, max_length=120, null=True)),
                ('bs_analysis_name', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Basespace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bs_email', models.EmailField(max_length=254)),
                ('bs_pwd', models.CharField(max_length=50)),
                ('bs_access_token', models.CharField(max_length=120)),
                ('bs_user_id', models.CharField(max_length=20)),
                ('novogene_bed_id', models.CharField(max_length=20)),
                ('novogene_gcc_id', models.CharField(max_length=20)),
                ('fulgent_bed_id', models.CharField(max_length=20)),
                ('fulgent_gcc_id', models.CharField(max_length=20)),
                ('bs_date_created', models.DateTimeField(auto_now_add=True)),
                ('bs_expiry_on', models.DateTimeField(null=True)),
                ('bs_credits', models.IntegerField(null=True)),
                ('bs_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Biosample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biosample_id', models.CharField(max_length=40, null=True)),
                ('biosample_type', models.CharField(max_length=20, null=True)),
                ('biosample_name', models.CharField(max_length=120, null=True)),
                ('biosample_path', models.CharField(max_length=480, null=True)),
                ('library_id', models.CharField(max_length=40, null=True)),
                ('biosample_created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientPortal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_information', models.CharField(max_length=500)),
                ('Physician_information', models.CharField(max_length=500)),
                ('Report_Date', models.DateTimeField(auto_now_add=True)),
                ('Cancer_Type', models.CharField(max_length=500)),
                ('Specimen', models.CharField(max_length=880)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=40)),
                ('bs_default_project', models.CharField(max_length=40)),
                ('bs_project_id', models.CharField(max_length=40)),
                ('project_type', models.CharField(max_length=40)),
                ('project_created_on', models.DateTimeField(auto_now_add=True)),
                ('bs_user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='KyvorPipeline.Basespace')),
            ],
            options={
                'get_latest_by': ['project_name'],
            },
        ),
        migrations.CreateModel(
            name='PipelineTO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=120)),
                ('biosample_t_file1', models.FileField(upload_to='', verbose_name=KyvorPipeline.models.Project)),
                ('biosample_t_file2', models.FileField(upload_to='', verbose_name=KyvorPipeline.models.Project)),
                ('biosample_t_file3', models.FileField(upload_to='', verbose_name=KyvorPipeline.models.Project)),
                ('biosample_t_file4', models.FileField(upload_to='', verbose_name=KyvorPipeline.models.Project)),
                ('project_cancer_type', models.CharField(max_length=120)),
                ('pipeline_initiated_on', models.DateTimeField(auto_now_add=True)),
                ('pipeline_finished_on', models.DateTimeField(blank=True)),
                ('pipeline_status', models.CharField(blank=True, max_length=120)),
                ('biosample_to_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='KyvorPipeline.Biosample')),
                ('project_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='KyvorPipeline.Project')),
            ],
        ),
        migrations.AddField(
            model_name='biosample',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='KyvorPipeline.Project'),
        ),
    ]
