# Generated by Django 3.0.8 on 2022-05-11 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KyvorPipeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'get_latest_by': ['project_name']},
        ),
    ]
