# Generated by Django 3.0.8 on 2022-05-11 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KyvorPipeline', '0002_auto_20220511_0520'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientPortal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_information', models.CharField(max_length=500)),
                ('Physician_information', models.CharField(max_length=500)),
                ('Report_Date', models.DateTimeField(auto_now_add=True)),
                ('Cancer_Type', models.CharField(max_length=500)),
                ('Specimen', models.CharField(max_length=880)),
            ],
        ),
    ]
