# Generated by Django 3.0.8 on 2022-05-18 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KyvorPipeline', '0003_patientportal'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientportal',
            name='Patient_ref_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
