# Generated by Django 3.0.8 on 2022-05-18 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KyvorPipeline', '0004_patientportal_patient_ref_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientportal',
            name='Patient_ref_id',
        ),
    ]
