# Generated by Django 3.0.8 on 2022-05-25 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KyvorPipeline', '0005_remove_patientportal_patient_ref_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FDAReports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Genes', models.CharField(max_length=100)),
                ('variants', models.CharField(max_length=200)),
                ('cancer_types', models.CharField(max_length=500)),
            ],
        ),
    ]
