# Generated by Django 3.0.8 on 2022-06-20 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KyvorPipeline', '0007_fda_sheets'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinical_DATA',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nct_id', models.CharField(blank=True, max_length=200, null=True)),
                ('official_title', models.TextField()),
                ('intervention', models.TextField()),
                ('variant_found', models.CharField(blank=True, max_length=200, null=True)),
                ('url', models.URLField(blank=True, max_length=2000, null=True)),
                ('BioMarker', models.CharField(blank=True, max_length=200, null=True)),
                ('Reference', models.TextField()),
                ('GENE', models.CharField(blank=True, max_length=200, null=True)),
                ('VARIANT', models.CharField(blank=True, max_length=200, null=True)),
                ('VARIANT_CDS', models.CharField(blank=True, max_length=200, null=True)),
                ('THERAPY', models.TextField()),
                ('EVIDENCE_STATEMENT_1', models.TextField()),
                ('EVIDENCE_STATEMENT_2', models.TextField()),
                ('Status', models.CharField(blank=True, max_length=200, null=True)),
                ('AF_VAF', models.CharField(blank=True, max_length=200, null=True)),
                ('CANCER_TYPES', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
